### ISSUE TITLE
Mobile-friendly design

### ISSUE THREAD

**Issue by jalovatt** [jalovatt/where-on-wikipedia#8]
Courtesy of @hafbau.

```css
@media screen(max-width: 500px) {
	  .title: {
			 left: auto;
			width: 100%;
			text-align: center;
			right: auto;
			position: relative;
			padding-top: 30px;
	  };
	.wiki.screen: {
		min-height: 80vh;
		width: 100%;
		top: 110vh;
		left: 0;
	};
	.game.screen: {
		height: 65vh;
		width: 100%;
		top: 24vh;
		left: 0;
	};
	.button-container: {
		width: 100%;
		top: 90vh;
		left: 0;
		bottom: auto;
		right: 0;
	};
}
```
